# Generated by Django 2.0.3 on 2018-03-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_1', models.CharField(max_length=2)),
                ('placar_2', models.CharField(max_length=2)),
                ('preco', models.CharField(choices=[('2', '2'), ('5', '5'), ('10', '10'), ('20', '20')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateField(auto_now=True)),
                ('placar_1', models.CharField(blank=True, max_length=2)),
                ('placar_2', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('sigla', models.CharField(max_length=4, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes_1', to='core.Selecao'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes_2', to='core.Selecao'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.Jogo'),
        ),
    ]
