# Generated by Django 2.0.3 on 2018-03-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=1)),
                ('selecao_do_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.Selecao')),
            ],
        ),
    ]
