# Generated by Django 2.0.3 on 2018-03-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='selecao_do_grupo',
        ),
    ]
