# Generated by Django 2.0.3 on 2018-03-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_grupo_selecao_do_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.Grupo'),
            preserve_default=False,
        ),
    ]
