# Generated by Django 2.0.3 on 2018-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_selecao_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='bandeira',
            field=models.ImageField(default=2, upload_to='galeria/original'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecao',
            name='gol_marc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecao',
            name='gol_sofr',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecao',
            name='pontos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
