# Generated by Django 2.0.3 on 2018-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180315_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ('horario',)},
        ),
        migrations.AlterModelOptions(
            name='selecao',
            options={'ordering': ('nome',), 'verbose_name': 'Seleção', 'verbose_name_plural': 'Seleções'},
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='bandeira',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='gol_marc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='gol_sofr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='pontos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
