# Generated by Django 2.0.3 on 2018-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180323_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='bandeira',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='gol_marc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='gol_sofr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='sigla',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
