# Generated by Django 2.0.3 on 2018-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180323_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='preco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
