# Generated by Django 2.0.3 on 2018-03-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180326_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='user',
            new_name='usuario',
        ),
    ]
