# Generated by Django 2.0.3 on 2018-03-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180326_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='usuario',
        ),
    ]
