# Generated by Django 2.0.3 on 2018-03-27 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_auto_20180326_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='aposta',
            name='usuario',
            field=models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
