# Generated by Django 2.0.3 on 2018-03-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180326_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='usuario',
            new_name='novo_user',
        ),
    ]
