# Generated by Django 2.0.3 on 2018-03-27 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180327_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='user_aposta',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_aposta', to=settings.AUTH_USER_MODEL),
        ),
    ]
