# Generated by Django 2.0.3 on 2018-03-27 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20180327_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='user_aposta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
