# Generated by Django 2.0.3 on 2018-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20180327_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='bandeira',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
