# Generated by Django 2.0.3 on 2018-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20180328_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='bandeira',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
