# Generated by Django 2.0.3 on 2018-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20180328_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='bandeira',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
